spring:
  application:
    name: eureka-ribbon


server:
  port: 8083
eureka:
  client:
    healthcheck:
      enabled: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    hostname: ${spring.application.name}
ribbon:
  okhttp:
    enabled: true



